name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm ci
    - run: npm test --if-present
    - run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/hamhibokka-backend
          
          # 현재 버전 백업
          git rev-parse HEAD > .current_commit
          
          # 새 코드 가져오기
          git fetch origin main
          git reset --hard origin/main
          
          # 의존성 설치 (변경된 경우만)
          npm ci --only=production
          
          # 빌드
          npm run build
          
          # 헬스체크용 임시 서버 시작
          pm2 start ecosystem.config.js --name temp-hamhibokka-backend || true
          
          # 헬스체크
          sleep 15
          HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -d '{"query":"query { __typename }"}' http://localhost:3000/graphql)
          
          if [ "$HEALTH_CHECK" = "200" ]; then
            echo "Health check passed"
            # 기존 서버 종료하고 새 서버로 교체
            pm2 delete hamhibokka-backend || true
            pm2 start ecosystem.config.js
            pm2 delete temp-hamhibokka-backend || true
            pm2 save
          else
            echo "Health check failed, rolling back"
            pm2 delete temp-hamhibokka-backend || true
            # 이전 커밋으로 롤백
            git reset --hard $(cat .current_commit)
            npm run build
            pm2 restart hamhibokka-backend
            exit 1
          fi